### PR TITLE
Fix indentation inconsistencies and remove extra spaces at end of line

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by jcxldn** [comment]
@yikjin 
Can you allow edits from maintainers? Then I can resolve these merge conflicts and get this PR merged.

**Comment by ghost** [comment]
@Prouser123 Edits from maintainers are already enabled by default

**Comment by jcxldn** [comment]
When I was reviewing your PR earlier, it seemed to have been disabled, and as such I could not resolve the merge conflict myself, as that involves committing to your branch.

**Review by jcxldn — APPROVED** [review]
Thanks for contributing! Your contribution will be merged soon.

**Pull request merged**
